# CI configuration
image: registry.gitlab.semanticlab.net/docker/py3full:latest
before_script:
    - sed -i s/-dev/".$(date +%Y%m%d.%H%M)"/g setup.py
    - export PROJECT=`/usr/bin/python3 -W ignore ./setup.py --name | awk 'NR==1{print $1}'`
    - export VERSION=`/usr/bin/python3 -W ignore ./setup.py --version | awk 'NR==1{print $1}'`
    - export PYWIKIBOT_NO_USER_CONFIG=1


stages:
    - test
    - build-package

# run all non-slow tests with coverage report and upload to Sonar
# sonar-scanner is not inside tox to ease the pain of env variable passing
pytest:
    stage: test
    script:
        - tox -q -e pytest
    after_script:
        - export PROJECT=`/usr/bin/python3 -W ignore ./setup.py --name | awk 'NR==1{print $1}'`
        - export VERSION=`/usr/bin/python3 -W ignore ./setup.py --version | awk 'NR==1{print $1}'`
        - sonar-scanner -D sonar.host.url=$sonarhost  -D sonar.login=$sonarlogin
    only:
        - branches
    tags:
        - docker

# lint the code
pylint:
    stage: test
    script:
        - tox -q -e pylint
    only:
        - branches
    when: manual
    tags:
        - docker

# run the as slow marked tests 
slowtest:
    stage: test
    script:
        - tox -q -e pytest-slow
    only:
        - branches
    when: manual
    tags:
        - docker

# CAVEAT: vulture returns exit code 1 if dead code is found, so the job will
# always fail *if* vulture finds something. 
vulture:
    stage: test
    script:
        - tox -q -e vulture
    only:
        - branches
    when: manual
    tags:
        - docker

# building and deploying
build:
    stage: build-package
    script:
        - chmod +x build-package.sh
        - ./build-package.sh
    only:
        - master
    tags:
        - shell-runner

