# CI configuration
image: registry.gitlab.semanticlab.net/core/ewrt:fullbase-with-py3
before_script:
    - python3 -m pip install -e .

stages:
    - tox

job_tox:
    stage: tox
    script:
        - python3 -m pip install pytest pytest-cov setuptools mock ujson numpy feedparser python-dateutil
        - tox
    only:
        - migration
    tags:
        - docker

