# CI configuration
#image: registry.gitlab.semanticlab.net/core/ewrt:fullbase-with-py3
image: registry.gitlab.semanticlab.net/docker/py3base:latest
before_script:
    - python3 -m pip --quiet install -e .

stages:
    - tox

job_tox:
    stage: tox
    script:
        - python3 -m pip --quiet install pytest pytest-cov setuptools mock ujson numpy feedparser python-dateutil future
        - tox
    only:
        - migration
    tags:
        - docker

