# CI configuration
image: registry.gitlab.semanticlab.net/docker/py3base:latest
before_script:
    - python3 -m pip --quiet install -e .

stages:
    - test
#    - build-package

pytest:
    stage: test
    script:
        - python3 -m pip --quiet install pytest pytest-cov setuptools mock ujson numpy feedparser python-dateutil future
        - tox
        - sonar-scanner
    only:
        - migration
    tags:
        - docker

pylint:
    stage: test
    script:
        - python3 -m pylint
    only:
        - migration
    when: manual
    tags:
        - docker

slowtest:
    stage: test
    script:
        - python3 -m pip --quiet install pytest pytest-cov setuptools mock ujson numpy feedparser python-dateutil future
        - pytest -m 'only slow' # or something with tox?? TODO

