# CI configuration
image: registry.gitlab.semanticlab.net/docker/py3base:latest
#before_script:
#    - python3 -m pip --quiet install -e .

stages:
    - test
#    - build-package

pytest:
    stage: test
    script:
        - tox -e pytest
        - sonar-scanner -D sonar.host.url=$sonarhost  -D sonar.login=$sonarlogin
    only:
        - migration
    tags:
        - docker

pylint:
    stage: test
    script:
        - tox -e pylint
    only:
        - migration
    when: manual
    tags:
        - docker

slowtest:
    stage: test
    script:
        - tox -e pytest-slow
    only:
        - migration
    when: manual
    tags:
        - docker

