language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pip install pytest-cov
  - py.test tests/ --cov=eWRT --cov-report xml