COUNTRY_CODES = [['country', 'ISO2Code', 'ISO3Code'],
                 ['http://www.wikidata.org/entity/Q77', 'UY', 'URU'],
                 ['http://www.wikidata.org/entity/Q221', 'MK', 'MKD'],
                 ['http://www.wikidata.org/entity/Q678', 'TO', 'TGA'],
                 ['http://www.wikidata.org/entity/Q697', 'NR', 'NRU'],
                 ['http://www.wikidata.org/entity/Q709', 'MH', 'MHL'],
                 ['http://www.wikidata.org/entity/Q712', 'FJ', 'FIJ'],
                 ['http://www.wikidata.org/entity/Q730', 'SR', 'SUR'],
                 ['http://www.wikidata.org/entity/Q736', 'EC', 'ECU'],
                 ['http://www.wikidata.org/entity/Q757', 'VC', 'VIN'],
                 ['http://www.wikidata.org/entity/Q766', 'JM', 'JAM'],
                 ['http://www.wikidata.org/entity/Q790', 'HT', 'HAI'],
                 ['http://www.wikidata.org/entity/Q792', 'SV', 'ESA'],
                 ['http://www.wikidata.org/entity/Q794', 'IR', 'IRI'],
                 ['http://www.wikidata.org/entity/Q796', 'IQ', 'IRQ'],
                 ['http://www.wikidata.org/entity/Q813', 'KG', 'KGZ'],
                 ['http://www.wikidata.org/entity/Q837', 'NP', 'NEP'],
                 ['http://www.wikidata.org/entity/Q843', 'PK', 'PAK'],
                 ['http://www.wikidata.org/entity/Q917', 'BT', 'BHU'],
                 ['http://www.wikidata.org/entity/Q954', 'ZW', 'ZIM'],
                 ['http://www.wikidata.org/entity/Q965', 'BF', 'BUR'],
                 ['http://www.wikidata.org/entity/Q983', 'GQ', 'GEQ'],
                 ['http://www.wikidata.org/entity/Q1008', 'CI', 'CIV'],
                 ['http://www.wikidata.org/entity/Q1011', 'CV', 'CPV'],
                 ['http://www.wikidata.org/entity/Q1013', 'LS', 'LES'],
                 ['http://www.wikidata.org/entity/Q1016', 'LY', 'LBA'],
                 ['http://www.wikidata.org/entity/Q1029', 'MZ', 'MOZ'],
                 ['http://www.wikidata.org/entity/Q1033', 'NG', 'NGR'],
                 ['http://www.wikidata.org/entity/Q1039', 'ST', 'STP'],
                 ['http://www.wikidata.org/entity/Q1041', 'SN', 'SEN'],
                 ['http://www.wikidata.org/entity/Q1050', 'SZ', 'SWZ'],
                 ['http://www.wikidata.org/entity/Q28', 'HU', 'HUN'],
                 ['http://www.wikidata.org/entity/Q29', 'ES', 'ESP'],
                 ['http://www.wikidata.org/entity/Q30', 'US', 'USA'],
                 ['http://www.wikidata.org/entity/Q31', 'BE', 'BEL'],
                 ['http://www.wikidata.org/entity/Q35', 'DK', 'DEN'],
                 ['http://www.wikidata.org/entity/Q37', 'LT', 'LTU'],
                 ['http://www.wikidata.org/entity/Q39', 'CH', 'SUI'],
                 ['http://www.wikidata.org/entity/Q40', 'AT', 'AUT'],
                 ['http://www.wikidata.org/entity/Q41', 'GR', 'GRE'],
                 ['http://www.wikidata.org/entity/Q45', 'PT', 'POR'],
                 ['http://www.wikidata.org/entity/Q96', 'MX', 'MEX'],
                 ['http://www.wikidata.org/entity/Q142', 'FR', 'FRA'],
                 ['http://www.wikidata.org/entity/Q148', 'CN', 'CHN'],
                 ['http://www.wikidata.org/entity/Q155', 'BR', 'BRA'],
                 ['http://www.wikidata.org/entity/Q183', 'DE', 'GER'],
                 ['http://www.wikidata.org/entity/Q184', 'BY', 'BLR'],
                 ['http://www.wikidata.org/entity/Q211', 'LV', 'LAT'],
                 ['http://www.wikidata.org/entity/Q212', 'UA', 'UKR'],
                 ['http://www.wikidata.org/entity/Q217', 'MD', 'MDA'],
                 ['http://www.wikidata.org/entity/Q222', 'AL', 'ALB'],
                 ['http://www.wikidata.org/entity/Q224', 'HR', 'CRO'],
                 ['http://www.wikidata.org/entity/Q225', 'BA', 'BIH'],
                 ['http://www.wikidata.org/entity/Q229', 'CY', 'CYP'],
                 ['http://www.wikidata.org/entity/Q230', 'GE', 'GEO'],
                 ['http://www.wikidata.org/entity/Q233', 'MT', 'MLT'],
                 ['http://www.wikidata.org/entity/Q236', 'ME', 'MNE'],
                 ['http://www.wikidata.org/entity/Q241', 'CU', 'CUB'],
                 ['http://www.wikidata.org/entity/Q244', 'BB', 'BAR'],
                 ['http://www.wikidata.org/entity/Q258', 'ZA', 'RSA'],
                 ['http://www.wikidata.org/entity/Q262', 'DZ', 'ALG'],
                 ['http://www.wikidata.org/entity/Q265', 'UZ', 'UZB'],
                 ['http://www.wikidata.org/entity/Q298', 'CL', 'CHI'],
                 ['http://www.wikidata.org/entity/Q334', 'SG', 'SIN'],
                 ['http://www.wikidata.org/entity/Q347', 'LI', 'LIE'],
                 ['http://www.wikidata.org/entity/Q398', 'BH', 'BRN'],
                 ['http://www.wikidata.org/entity/Q399', 'AM', 'ARM'],
                 ['http://www.wikidata.org/entity/Q403', 'RS', 'SRB'],
                 ['http://www.wikidata.org/entity/Q414', 'AR', 'ARG'],
                 ['http://www.wikidata.org/entity/Q424', 'KH', 'CAM'],
                 ['http://www.wikidata.org/entity/Q574', 'TL', 'TLS'],
                 ['http://www.wikidata.org/entity/Q657', 'TD', 'CHA'],
                 ['http://www.wikidata.org/entity/Q664', 'NZ', 'NZL'],
                 ['http://www.wikidata.org/entity/Q668', 'IN', 'IND'],
                 ['http://www.wikidata.org/entity/Q686', 'VU', 'VAN'],
                 ['http://www.wikidata.org/entity/Q695', 'PW', 'PLW'],
                 ['http://www.wikidata.org/entity/Q717', 'VE', 'VEN'],
                 ['http://www.wikidata.org/entity/Q739', 'CO', 'COL'],
                 ['http://www.wikidata.org/entity/Q754', 'TT', 'TRI'],
                 ['http://www.wikidata.org/entity/Q769', 'GD', 'GRN'],
                 ['http://www.wikidata.org/entity/Q774', 'GT', 'GUA'],
                 ['http://www.wikidata.org/entity/Q781', 'AG', 'ANT'],
                 ['http://www.wikidata.org/entity/Q784', 'DM', 'DMA'],
                 ['http://www.wikidata.org/entity/Q786', 'DO', 'DOM'],
                 ['http://www.wikidata.org/entity/Q801', 'IL', 'ISR'],
                 ['http://www.wikidata.org/entity/Q805', 'YE', 'YEM'],
                 ['http://www.wikidata.org/entity/Q819', 'LA', 'LAO'],
                 ['http://www.wikidata.org/entity/Q822', 'LB', 'LIB'],
                 ['http://www.wikidata.org/entity/Q836', 'MM', 'MYA'],
                 ['http://www.wikidata.org/entity/Q842', 'OM', 'OMA'],
                 ['http://www.wikidata.org/entity/Q846', 'QA', 'QAT'],
                 ['http://www.wikidata.org/entity/Q851', 'SA', 'KSA'],
                 ['http://www.wikidata.org/entity/Q858', 'SY', 'SYR'],
                 ['http://www.wikidata.org/entity/Q863', 'TJ', 'TJK'],
                 ['http://www.wikidata.org/entity/Q869', 'TH', 'THA'],
                 ['http://www.wikidata.org/entity/Q878', 'AE', 'UAE'],
                 ['http://www.wikidata.org/entity/Q884', 'KR', 'KOR'],
                 ['http://www.wikidata.org/entity/Q889', 'AF', 'AFG'],
                 ['http://www.wikidata.org/entity/Q912', 'ML', 'MLI'],
                 ['http://www.wikidata.org/entity/Q916', 'AO', 'ANG'],
                 ['http://www.wikidata.org/entity/Q962', 'BJ', 'BEN'],
                 ['http://www.wikidata.org/entity/Q970', 'KM', 'COM'],
                 ['http://www.wikidata.org/entity/Q974', 'CD', 'COD'],
                 ['http://www.wikidata.org/entity/Q977', 'DJ', 'DJI'],
                 ['http://www.wikidata.org/entity/Q986', 'ER', 'ERI'],
                 ['http://www.wikidata.org/entity/Q1009', 'CM', 'CMR'],
                 ['http://www.wikidata.org/entity/Q1014', 'LR', 'LBR'],
                 ['http://www.wikidata.org/entity/Q1019', 'MG', 'MAD'],
                 ['http://www.wikidata.org/entity/Q1027', 'MU', 'MRI'],
                 ['http://www.wikidata.org/entity/Q1028', 'MA', 'MAR'],
                 ['http://www.wikidata.org/entity/Q1030', 'NA', 'NAM'],
                 ['http://www.wikidata.org/entity/Q1042', 'SC', 'SEY'],
                 ['http://www.wikidata.org/entity/Q1044', 'SL', 'SLE'],
                 ['http://www.wikidata.org/entity/Q1049', 'SD', 'SUD'],
                 ['http://www.wikidata.org/entity/Q15180', 'SU', 'URS'],
                 ['http://www.wikidata.org/entity/Q16', 'CA', 'CAN'],
                 ['http://www.wikidata.org/entity/Q17', 'JP', 'JPN'],
                 ['http://www.wikidata.org/entity/Q20', 'NO', 'NOR'],
                 ['http://www.wikidata.org/entity/Q27', 'IE', 'IRL'],
                 ['http://www.wikidata.org/entity/Q32', 'LU', 'LUX'],
                 ['http://www.wikidata.org/entity/Q33', 'FI', 'FIN'],
                 ['http://www.wikidata.org/entity/Q34', 'SE', 'SWE'],
                 ['http://www.wikidata.org/entity/Q36', 'PL', 'POL'],
                 ['http://www.wikidata.org/entity/Q38', 'IT', 'ITA'],
                 ['http://www.wikidata.org/entity/Q43', 'TR', 'TUR'],
                 ['http://www.wikidata.org/entity/Q79', 'EG', 'EGY'],
                 ['http://www.wikidata.org/entity/Q114', 'KE', 'KEN'],
                 ['http://www.wikidata.org/entity/Q115', 'ET', 'ETH'],
                 ['http://www.wikidata.org/entity/Q117', 'GH', 'GHA'],
                 ['http://www.wikidata.org/entity/Q145', 'GB', 'GBR'],
                 ['http://www.wikidata.org/entity/Q159', 'RU', 'RUS'],
                 ['http://www.wikidata.org/entity/Q189', 'IS', 'ISL'],
                 ['http://www.wikidata.org/entity/Q191', 'EE', 'EST'],
                 ['http://www.wikidata.org/entity/Q213', 'CZ', 'CZE'],
                 ['http://www.wikidata.org/entity/Q214', 'SK', 'SVK'],
                 ['http://www.wikidata.org/entity/Q215', 'SI', 'SLO'],
                 ['http://www.wikidata.org/entity/Q218', 'RO', 'ROU'],
                 ['http://www.wikidata.org/entity/Q219', 'BG', 'BUL'],
                 ['http://www.wikidata.org/entity/Q227', 'AZ', 'AZE'],
                 ['http://www.wikidata.org/entity/Q228', 'AD', 'AND'],
                 ['http://www.wikidata.org/entity/Q232', 'KZ', 'KAZ'],
                 ['http://www.wikidata.org/entity/Q235', 'MC', 'MON'],
                 ['http://www.wikidata.org/entity/Q238', 'SM', 'SMR'],
                 ['http://www.wikidata.org/entity/Q242', 'BZ', 'BIZ'],
                 ['http://www.wikidata.org/entity/Q252', 'ID', 'INA'],
                 ['http://www.wikidata.org/entity/Q408', 'AU', 'AUS'],
                 ['http://www.wikidata.org/entity/Q419', 'PE', 'PER'],
                 ['http://www.wikidata.org/entity/Q423', 'KP', 'PRK'],
                 ['http://www.wikidata.org/entity/Q672', 'TV', 'TUV'],
                 ['http://www.wikidata.org/entity/Q683', 'WS', 'SAM'],
                 ['http://www.wikidata.org/entity/Q685', 'SB', 'SOL'],
                 ['http://www.wikidata.org/entity/Q691', 'PG', 'PNG'],
                 ['http://www.wikidata.org/entity/Q702', 'FM', 'FSM'],
                 ['http://www.wikidata.org/entity/Q710', 'KI', 'KIR'],
                 ['http://www.wikidata.org/entity/Q711', 'MN', 'MGL'],
                 ['http://www.wikidata.org/entity/Q733', 'PY', 'PAR'],
                 ['http://www.wikidata.org/entity/Q734', 'GY', 'GUY'],
                 ['http://www.wikidata.org/entity/Q750', 'BO', 'BOL'],
                 ['http://www.wikidata.org/entity/Q760', 'LC', 'LCA'],
                 ['http://www.wikidata.org/entity/Q763', 'KN', 'SKN'],
                 ['http://www.wikidata.org/entity/Q778', 'BS', 'BAH'],
                 ['http://www.wikidata.org/entity/Q783', 'HN', 'HON'],
                 ['http://www.wikidata.org/entity/Q800', 'CR', 'CRC'],
                 ['http://www.wikidata.org/entity/Q804', 'PA', 'PAN'],
                 ['http://www.wikidata.org/entity/Q810', 'JO', 'JOR'],
                 ['http://www.wikidata.org/entity/Q811', 'NI', 'NCA'],
                 ['http://www.wikidata.org/entity/Q817', 'KW', 'KUW'],
                 ['http://www.wikidata.org/entity/Q826', 'MV', 'MDV'],
                 ['http://www.wikidata.org/entity/Q833', 'MY', 'MAS'],
                 ['http://www.wikidata.org/entity/Q854', 'LK', 'SRI'],
                 ['http://www.wikidata.org/entity/Q874', 'TM', 'TKM'],
                 ['http://www.wikidata.org/entity/Q881', 'VN', 'VIE'],
                 ['http://www.wikidata.org/entity/Q902', 'BD', 'BAN'],
                 ['http://www.wikidata.org/entity/Q921', 'BN', 'BRU'],
                 ['http://www.wikidata.org/entity/Q924', 'TZ', 'TAN'],
                 ['http://www.wikidata.org/entity/Q928', 'PH', 'PHI'],
                 ['http://www.wikidata.org/entity/Q929', 'CF', 'CAF'],
                 ['http://www.wikidata.org/entity/Q945', 'TG', 'TOG'],
                 ['http://www.wikidata.org/entity/Q948', 'TN', 'TUN'],
                 ['http://www.wikidata.org/entity/Q953', 'ZM', 'ZAM'],
                 ['http://www.wikidata.org/entity/Q958', 'SS', 'SSD'],
                 ['http://www.wikidata.org/entity/Q963', 'BW', 'BOT'],
                 ['http://www.wikidata.org/entity/Q967', 'BI', 'BDI'],
                 ['http://www.wikidata.org/entity/Q971', 'CG', 'CGO'],
                 ['http://www.wikidata.org/entity/Q1000', 'GA', 'GAB'],
                 ['http://www.wikidata.org/entity/Q1005', 'GM', 'GAM'],
                 ['http://www.wikidata.org/entity/Q1006', 'GN', 'GUI'],
                 ['http://www.wikidata.org/entity/Q1007', 'GW', 'GBS'],
                 ['http://www.wikidata.org/entity/Q1020', 'MW', 'MAW'],
                 ['http://www.wikidata.org/entity/Q1025', 'MR', 'MTN'],
                 ['http://www.wikidata.org/entity/Q1032', 'NE', 'NIG'],
                 ['http://www.wikidata.org/entity/Q1036', 'UG', 'UGA'],
                 ['http://www.wikidata.org/entity/Q1037', 'RW', 'RWA'],
                 ['http://www.wikidata.org/entity/Q1045', 'SO', 'SOM'],
                 ['http://www.wikidata.org/entity/Q29999', 'NL', 'NED'],
                 ]



COUNTRY_ISO2_CODES_DICT = {entry[0]: entry[1] for entry in COUNTRY_CODES[1:]}

# # Code to import ISO codes for non-independent territorries/obsolete countries
# # should we decide to use them too:
#
#
# countries_old = copy.copy(COUNTRY_ISO2_CODES_DICT)
# import pywikibot
# QUERY = """
# SELECT ?item WHERE{
#     ?item wdt:P297 ?iso_code
# }
# """
# site = pywikibot.Site('wikidata', 'wikidata')
# from eWRT.ws.wikidata.preferred_claim_value import attribute_preferred_value
#
# import pywikibot.pagegenerators
# generator = pywikibot.pagegenerators.WikidataSPARQLPageGenerator(
#             QUERY, site=site)
#
# for result in generator:
#     result.get()
#     # print result.id, result.claims['P297']
#     if 'http://www.wikidata.org/entity/'+ result.id not in COUNTRY_ISO2_CODES_DICT:
#         COUNTRY_ISO2_CODES_DICT['http://www.wikidata.org/entity/'+ result.id ] = \
#         attribute_preferred_value(result.claims['P297'])
#         print('adding code for country: ' + result.id)
